structure(list(url = "http://httpbin.org/status/404", status_code = 404L, 
    headers = structure(list(date = "Mon, 31 May 2021 21:08:55 GMT", 
        `content-type` = "text/html; charset=utf-8", `content-length` = "0", 
        connection = "keep-alive", server = "gunicorn/19.9.0", 
        `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Mon, 31 May 2021 21:08:55 GMT", 
            `content-type` = "text/html; charset=utf-8", `content-length` = "0", 
            connection = "keep-alive", server = "gunicorn/19.9.0", 
            `access-control-allow-origin` = "*", `access-control-allow-credentials` = "true"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1622495335, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.012923, 
    connect = 0.095053, pretransfer = 0.095148, starttransfer = 0.180033, 
    total = 0.180065)), class = "response")
